### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by poisondima** [Vedeneb/HA-SmartThings-Find#1]
Hi, thank you so much for trying to do the long awaited integration!
There is a small remark about encoding, for example Russian language.
Here is how it looks like on the Samsung website:
![изображение](https://github.com/Vedeneb/HA-SmartThings-Find/assets/39500249/bca1d34c-806d-4243-b644-0e65f5c42c0d)
And here is how it is displayed in HA:
![изображение](https://github.com/Vedeneb/HA-SmartThings-Find/assets/39500249/2d54d89c-78a4-47e5-8f26-ca9ddaf6d3c4)
Maybe the encoding is not set to utf-8

**Comment by Vedeneb** [comment]
Thanks for reporting, you were right in your assumption. Apparently the API returned data in some weird encoding instead of UTF-8 because I did not specify the `Accept`-Header. Setting this to `application/json` seems to have fixed it.

**Comment by poisondima** [comment]
Thanks, it's showing correctly now.
![изображение](https://github.com/Vedeneb/HA-SmartThings-Find/assets/39500249/967e8287-2f4f-4bc3-9b93-0ddefc0ff9b0)
