### ISSUE TITLE
apostrophe as string get bad read from smart things

### ISSUE THREAD

**Issue by zivgin** [Vedeneb/HA-SmartThings-Find#12]
I have items that are names with apostrophe (e.g. this sign '), for examples: _Ziv's S23 Ultra.
Instead of ' i get this: &amp;#39;

So instead of: _Ziv's S23 Ultra_
I get: _Ziv&amp;#39;s S23 Ultra_

Chatgpt response:
o dynamically fix the issue with HTML entities being displayed instead of apostrophes in the HA-SmartThings-Find repository, you should decode HTML entities in the relevant parts of the code where data is processed or displayed.

Steps:
Modify the Data Processing:
Update the Python code to decode HTML entities when fetching or processing data. For example, in custom_components/smartthings_find/__init__.py or other relevant files:

python
Copy code
import html

def fetch_and_process_data():
    # Fetch data
    data = fetch_data_from_smartthings()
    # Decode HTML entities
    data['name'] = html.unescape(data.get('name'))
    # Process data
    process_device_name(data['name'])
Check Rendering in Templates:
If the issue is also in the frontend, ensure that HTML entities are decoded before rendering the text. You can create a utility function in JavaScript:

javascript
Copy code
function decodeHtmlEntities(html) {
    var txt = document.createElement("textarea");
    txt.innerHTML = html;
    return txt.value;
}

function renderDeviceName(name) {
    var decodedName = decodeHtmlEntities(name);
    document.getElementById('device-name').innerText = decodedName;
}
By integrating these utility functions, you can dynamically handle and decode HTML entities, ensuring that names like Ziv's S23 Ultra are displayed correctly. This should be applied wherever data is fetched, processed, or rendered within the codebase.

For more detailed instructions, you can refer to the [HA-SmartThings-Find repository](https://github.com/Vedeneb/HA-SmartThings-Find).

**Comment by Vedeneb** [comment]
Hi, just released v0.2.0 which should fix this issue.

**Comment by zivgin** [comment]
Thank you! it works!
