### ISSUE TITLE
Setup Failure

### ISSUE THREAD

**Issue by emoleary** [Vedeneb/HA-SmartThings-Find#3]
I've been trying to setup HA-SmartThings-Find for a few days now. Every time I try to navigate to the integration using the button from the README.md file, I end up here:
![Screenshot from 2024-05-27 15-31-47](https://github.com/Vedeneb/HA-SmartThings-Find/assets/74734235/71577448-f0c1-4a0c-b2b9-b412d3143030)

This was after moving custom_components/smart_things_find into my config directory and restarting.
![Screenshot from 2024-05-27 15-37-42](https://github.com/Vedeneb/HA-SmartThings-Find/assets/74734235/4af2af16-f3d3-4e02-b94a-afdc4222edf9)

Finally, I did not see SmartThings Find in my list of available integrations at all. 
![Screenshot from 2024-05-27 15-32-56](https://github.com/Vedeneb/HA-SmartThings-Find/assets/74734235/dd32424a-a5f8-4909-9e27-79c769719991)

(Any help, thanks!)

**Comment by Vedeneb** [comment]
Hi,
you need to have a folder called "custom_components". If this is the first custom integration you are installing, you need to manually create that folder. Put the "smartthings_find" directory inside "custom_components". 

I also recommend you to install the "Studio Code Server Add-On" as this allows managing files in a much easier way compared to the command line.

**Comment by Vedeneb** [comment]
Also, if you download this whole repository, you will already have the correct directory structure. Simply copy the whole "custom_components" directory into your config directory (not just the smartthings_find folder, but the whole custom_components folder).

**Comment by Vedeneb** [comment]
I just added HACS support, you don't need to manually install anymore.
