### ISSUE TITLE
Feature request: Last seen as a separate attribute

### ISSUE THREAD

**Issue by quack3d** [Vedeneb/HA-SmartThings-Find#4]
I assume one of those timestamps in one of the attributes is the 'last seen' date and time. Can you perhaps add that as a separate attribute? Ideally already converted to local time. I'd like to quickly see when an item was last found.

**Comment by Vedeneb** [comment]
Hi, 
just released v0.1.3 which adds a new attribute `last_seen`. Let me know if this fits your usecase :)

**Comment by quack3d** [comment]
Perfect! Thanks! What's the polling rate btw?

**Comment by Vedeneb** [comment]
The polling rate is two minutes: https://github.com/Vedeneb/HA-SmartThings-Find/blob/8d68bbac4a41f8d1727fdc5db8e0ba6a188060d8/custom_components/smartthings_find/__init__.py#L83
