### ISSUE TITLE
Error setting up entry  SmartThings Find for smartthings_find

### ISSUE THREAD

**Issue by liamlain** [Vedeneb/HA-SmartThings-Find#6]
error showing after restart

Logger: homeassistant.config_entries
Source: config_entries.py:584
First occurred: 12:22:16 AM (3 occurrences)
Last logged: 12:23:15 AM

Error setting up entry LAI SmartThings Find for smartthings_find
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthings_find/__init__.py", line 33, in async_setup_entry
    await fetch_csrf(hass, session)
  File "/config/custom_components/smartthings_find/utils.py", line 215, in fetch_csrf
    hass.data[DOMAIN]["_csrf"] = csrf_token
    ~~~~~~~~~^^^^^^^^
KeyError: 'smartthings_find'

**Comment by Vedeneb** [comment]
Hi,
I need some more info as I can't reprocuce this.

- Could you ever set the integration up or did this already happen the first time you set this integration up?
- Was it a one-time problem or does it happen after every restart?
- Did you try deleting the integration and adding it again?
- What version of Home Assistant are you using?

**Comment by liamlain** [comment]
Could you ever set the integration up or did this already happen the first time you set this integration up?
-yes the intergration is set up and work,but after restart core,the error showing 
Was it a one-time problem or does it happen after every restart?
-one time problem
Did you try deleting the integration and adding it again?
-yes deleted the intergration and restart.
What version of Home Assistant are you using?
2024.5.5

but now the integration since automatically work and the entity is working now,i got no clue what causing tihs

**Comment by Vedeneb** [comment]
👍
I'm not sure either, to be honest I have no clue what the error could mean...
Glad it's working fine now for you, let me know if you have any other problems.

**Comment by jampez77** [comment]
I have this same error following a restart. I've just update to 2024.6.1.

Tired all the above steps and now i get no devices at all where previously I had 4, including a smart tag.
