### ISSUE TITLE
Geocoded Location

### ISSUE THREAD

**Issue by stevewrightnz** [Vedeneb/HA-SmartThings-Find#7]
Given that these things display on a map in the SmartThings App, how easy would it be to add the geolocated location as an additional sensor?

Just a feature request if you've managed to reverse engineer the API that far :)

SteveW

**Comment by Vedeneb** [comment]
Hi,
can you show me an example (screenshot) of what exactly you mean? I don't see a gelocated location on SmartThings Find Website.

**Comment by stevewrightnz** [comment]
Hi
Looking at SmartThings Find devices are plotted on a map like this. 

![image](https://github.com/Vedeneb/HA-SmartThings-Find/assets/2554268/d6fbfe32-dd68-4dec-b154-7d1dec4fa940)

To do this you need the co-ordinates of the device.

These co-ordinates can be converted to a local address, I'd guess using a script of some sort, and my Samsung phone gives something like this based on a sensor from the HA Mobile App called sensor.sm_a346e_geocoded_location. 

![image](https://github.com/Vedeneb/HA-SmartThings-Find/assets/2554268/0c1d31b4-1a23-42e7-8430-8f27bd7ec336)

Steve

**Comment by Vedeneb** [comment]
Thanks for clarifying. However this is out of scope for the integration, as this is nothing I could get from the SmartThings Find API. This would require using another service, such as Google API. I think Home Assistant also uses Google to get the geocoded location for the mobile app sensors.

**Comment by stevewrightnz** [comment]
all good
________________________________
