### ISSUE TITLE
I Can see my devices but not my smarttag

### ISSUE THREAD

**Issue by furiiibond** [Vedeneb/HA-SmartThings-Find#9]

**Comment by Vedeneb** [comment]
Hi, sorry, without any more information I can not help.

**Comment by furiiibond** [comment]
Sorry I made this post so quickly, first of all thank you for this intergation that I was really looking forward to! 

The problem is that in my device on HA I can not see my smart tag.
![image](https://github.com/Vedeneb/HA-SmartThings-Find/assets/64899500/d03826d1-40d7-40b7-8703-894c92e8c0d0)
But it's present in my app in the same account as the others.
![image](https://github.com/Vedeneb/HA-SmartThings-Find/assets/64899500/6db6b443-4535-4651-a906-92da3f5bd13e)

**Comment by Vedeneb** [comment]
As stated in the Readme, please check what devices you see in the SmartThings Find website. The app and website are two different things.

**Comment by furiiibond** [comment]
I don't see the smarttag on the website, do you have any idea how I could make it appear here?
![image](https://github.com/Vedeneb/HA-SmartThings-Find/assets/64899500/c1961879-3481-484f-80be-ac3abfc97b7c)

**Comment by Vedeneb** [comment]
Are you sure you're using the same account? Maybe the Tag belongs to another account and is just shared with your account? Just guessing though...

**Comment by furiiibond** [comment]
It's the same account though, I just checked again, it's a smarttag 2

**Comment by furiiibond** [comment]
I tried to reset my smarttag, remove my home in smartthings app but still have the issue

**Comment by Vedeneb** [comment]
Sorry, I really don't know what could be the reason. Maybe it's a country restriction or something? I suggest you to ask Samsung Support why you don't see the device on the SmartThings Website.

Since this is not a problem with the integration, I'm going to close the issue.
